## Numpy
 - numeric operations
 - its works as creating arrays and mathematical operations and statistical operations

### importing numpy

In [3]:
import numpy as np

In [5]:
dir(np)#  to see numpy methods.

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [6]:
len(dir(np))# number of numpy methods

620

## Creating an array

In [7]:
a1=np.array([1,2,3,4,5])#single dimension array

In [8]:
print(a1)

[1 2 3 4 5]


In [9]:
a1.ndim # tocheck the number of dimensions

1

In [10]:
a1.size  #to check the size of the array.

5

In [11]:
a1.shape # it shows the number of rows and colums

(5,)

In [14]:
a2=np.array([[1,2,3,4],[2,3,4,5]])

In [15]:
print(a2)

[[1 2 3 4]
 [2 3 4 5]]


In [16]:
a2.ndim# number of dimensions

2

In [17]:
a2.shape # shape of the array

(2, 4)

In [18]:
a2.size #size of 2d array

8

In [22]:
a3=np.arange(1,31) # arange method 

In [23]:
a3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [28]:
a3.reshape(5,6) # reshapes the array in our perspective matrix order.

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [33]:
a3.reshape(2,15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [34]:
n=a3.reshape(2,15)

In [35]:
n.shape

(2, 15)

In [41]:
k=n.reshape(3,10)

In [47]:
print(k)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


## Accesing the 16 number in array

In [46]:
k[1][5] #by indexing

16

In [48]:
k[1:2,5:6] # by slicing

array([[16]])

In [49]:
k[0:1,5:6] # by slicing

array([[6]])

In [51]:
k[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
k[1:2,1:6:2]# slicing with differences

array([[12, 14, 16]])

In [63]:
a4=k.reshape(6,5)

In [64]:
a4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [66]:
a4[4:6,2:4] #slicing the multiple elements in an array.

array([[23, 24],
       [28, 29]])

In [69]:
a4[0:6:5,1:5:3]

array([[ 2,  5],
       [27, 30]])

## random method  or rand method

In [70]:
np.random.random()

0.07149446090623668

In [73]:
np.random.random(100)

array([0.12218772, 0.95104533, 0.30359287, 0.76463397, 0.17103344,
       0.82942407, 0.88826962, 0.16136844, 0.35468628, 0.26000522,
       0.12520535, 0.71788005, 0.39953105, 0.57744419, 0.26637076,
       0.46331193, 0.35189337, 0.47424049, 0.07865658, 0.75987368,
       0.38785217, 0.40657147, 0.45735797, 0.56261757, 0.37957702,
       0.15603518, 0.39211644, 0.97938784, 0.06449555, 0.01416194,
       0.59986701, 0.37615465, 0.44487043, 0.18259235, 0.28425688,
       0.47136365, 0.89021048, 0.10611243, 0.91959973, 0.26399821,
       0.62443496, 0.8609166 , 0.24676803, 0.05248472, 0.93667861,
       0.64551715, 0.42962042, 0.85566401, 0.95363241, 0.12574261,
       0.41091532, 0.7585635 , 0.60149444, 0.15558453, 0.52595846,
       0.11886866, 0.30204415, 0.02307309, 0.78756667, 0.73851062,
       0.01009814, 0.26619136, 0.30498206, 0.56557507, 0.29585481,
       0.76697344, 0.54364612, 0.02715848, 0.67716256, 0.52816392,
       0.68468617, 0.06505994, 0.22706927, 0.34004002, 0.64973

In [75]:
np.random.rand(10)

array([0.49059708, 0.72084077, 0.15581584, 0.93495433, 0.78907878,
       0.80314688, 0.44169141, 0.7470884 , 0.63112308, 0.36128832])

## randn is generate both negative and postive values

In [76]:
np.random.randn(10)

array([-1.68728627, -1.23219537,  0.15054416, -0.17608664, -0.17779154,
       -0.19594918,  0.76741687,  0.7151306 ,  1.08666361,  1.20416388])

## randint will generte random number with in range


In [77]:
np.random.randint(10)

2

In [79]:
np.random.randint(1,100,10) # it genrates 10 random numbers within range.

array([30, 49, 19, 42, 69, 23,  7,  4,  3, 48])

In [82]:
l=np.random.randint(1,1000,100)

In [83]:
l

array([447, 989, 164, 893,  42, 279,  82, 573, 284, 161, 927, 793, 295,
       265, 510, 888, 977, 945, 992, 262, 382, 565, 623, 108, 877, 281,
       517, 337, 345, 758, 210, 597, 186, 513, 763, 341, 737, 674, 579,
       494, 497, 227, 172, 106, 307, 426, 610, 808, 766, 740, 536, 988,
       892, 621, 607, 455, 770, 751, 822, 564, 679, 502, 990, 949, 321,
       738, 744, 981, 507, 329, 126, 222, 763, 366, 752, 242, 657,   9,
        49, 702, 816, 991, 649, 156, 915, 594, 819,  27,  16, 506, 485,
       145, 375, 962, 692, 185, 607, 703, 853, 450])

## printing only even numbers

In [87]:
for i in l:
    if i%2==0: # or l[l%2==0]
        print(i)

164
42
82
284
510
888
992
262
382
108
758
210
186
674
494
172
106
426
610
808
766
740
536
988
892
770
822
564
502
990
738
744
126
222
366
752
242
702
816
156
594
16
506
962
692
450


## printing only odd numbers

In [91]:
for i in l:   # or l[l%2!=0]
    if i%2!=0:
        print(i)


447
989
893
279
573
161
927
793
295
265
977
945
565
623
877
281
517
337
345
597
513
763
341
737
579
497
227
307
621
607
455
751
679
949
321
981
507
329
763
657
9
49
991
649
915
819
27
485
145
375
185
607
703
853
